//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace var3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriversCars
    {
        public string idDriver { get; set; }
        public string idCar { get; set; }
        public System.DateTime dateStartHaving { get; set; }
        public Nullable<System.DateTime> dateEndhaving { get; set; }

        public string GetStateNumber { get => Car.StateNumber; }
        public string GetMark { get => Car.mark.ToString(); }
        public string GetModel { get => Car.model; }
        public string GetColor { get => Car.color; }
        public string GetYear { get => Car.madeYear.ToString(); }

        public string FioDriver { get => Driver.name; }



        public virtual Car Car { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
